name: fashion_store_app
description: Fashion Store Mobile App - E-commerce application for fashion products
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296

  # API
  http: ^1.2.2

  # local storage (lưu token sau login)
  shared_preferences: ^2.3.2

  # image
  cached_network_image: ^3.4.1

  # animation (dùng cho loading sau này)
  lottie: ^3.1.2

  # Định dạng ngày tháng và tiền tệ
  intl: ^0.18.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1 # Hoặc phiên bản mới nhất

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/products/       # Thư mục chứa ảnh sản phẩm
    - assets/                # Thư mục chung nếu có thêm hình, icon, background...
